### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Mister-Curious** [Rashnain/SaveMod#13]
Hey. Your amazing mod is an essential part of the gameplay I have with my young child (dying isn't really a bad thing when you have backups). So my question is, will there eventually be support for 1.21 ?

Thanks!

**Comment by Tigler-god** [comment]
可以更新到1.21吗，我真的很需要您的mod，我是来自中国的玩家。希望您可以快快更新

**Comment by Rashnain** [comment]
I've release the update, see [here](https://modrinth.com/mod/savemod/version/djxsPfhb).

**Comment by Mister-Curious** [comment]
Awesome. Thanks so much
