### ISSUE TITLE
When Up to 1.21? plz.... Ireally need.

### ISSUE THREAD

**Issue by Tigler-god** [Rashnain/SaveMod#16]
Greetings, may I request an upgrade to version 1.21? I have a vital need for this update.
As a gamer from China, I've noticed a span of eight months without updates from you, and I urgently require this update.

**Comment by Rashnain** [comment]
I've release the update, see [here](https://modrinth.com/mod/savemod/version/djxsPfhb).

**Comment by Mister-Curious** [comment]
> I've release the update, see [here](https://modrinth.com/mod/savemod/version/djxsPfhb).

THANK YOU !!!!

**Comment by Tigler-god** [comment]
Thank you so much for the update. I've already started using it and it's truly great.
